[corpus]
# you may have to adjust paths if you pull this stuff from github
name="SWIKO"
docid_file="/mnt/biggie/dakoda_data/WTLD-L2/WTLD-L2-Daten/csv/DaF/docids.tsv" # has no header
learner_metadata_table="/mnt/biggie/dakoda_metadaten/ap_meta_daten_mapping/SWIK-Lx_Metadaten_students_infos_D_ap_25-04-22.tsv"
corpus_metadata_table="/mnt/biggie/dakoda_metadaten/ap_meta_daten_mapping/Metadaten_Korpora_fuer_Josef_25_04-16.xlsx"
metadata_output_dir="/mnt/biggie/dakoda_data/WTLD-L2/WTLD-L2-Daten/csv/DaF/metadata"
lang_info_lookup="/mnt/biggie/dakoda_metadaten/ap_meta_daten_mapping/WordOrder_sauber-fuer-Josef_2025-03-12.tsv"
task_description_table="/mnt/biggie/dakoda_metadaten/ap_meta_daten_mapping/taskid2taskdesc.tsv"
transcriber_table="/mnt/biggie/dakoda_data/WTLD-L2/WTLD-L2-Daten/SWIKO_merged_transcriber_table.tsv"
